/**
 * Simple API to gather and rank questions during talks
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: antony.guinard@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _SWG_SWGPublicApi_H_
#define _SWG_SWGPublicApi_H_

#include "SWGHttpRequest.h"

#include "SWGQuestion.h"

#include <QObject>

namespace Swagger {

class SWGPublicApi: public QObject {
    Q_OBJECT

public:
    SWGPublicApi();
    SWGPublicApi(QString host, QString basePath);
    ~SWGPublicApi();

    QString host;
    QString basePath;

    void addQuestion(SWGQuestion question);
    void listQuestions();
    void upvote(qint64 id);
    
private:
    void addQuestionCallback (HttpRequestWorker * worker);
    void listQuestionsCallback (HttpRequestWorker * worker);
    void upvoteCallback (HttpRequestWorker * worker);
    
signals:
    void addQuestionSignal(SWGQuestion* summary);
    void listQuestionsSignal(QList<SWGQuestion*>* summary);
    void upvoteSignal(qint64 summary);
    
};
}
#endif
