/**
 * Simple API to gather and rank questions during talks
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: antony.guinard@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGQuestion.h
 * 
 * 
 */

#ifndef SWGQuestion_H_
#define SWGQuestion_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGQuestion: public SWGObject {
public:
    SWGQuestion();
    SWGQuestion(QString* json);
    virtual ~SWGQuestion();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGQuestion* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getQuestion();
    void setQuestion(QString* question);

    qint64 getVotes();
    void setVotes(qint64 votes);


private:
    qint64 id;
    QString* question;
    qint64 votes;
};

} /* namespace Swagger */

#endif /* SWGQuestion_H_ */
